package com.inventory.backend.infrastructure.persistence;

import com.inventory.backend.infrastructure.persistence.entity.PermissionEntity;
import com.inventory.backend.infrastructure.persistence.entity.RoleEntity;
import com.inventory.backend.infrastructure.persistence.entity.UserEntity;
import com.inventory.backend.infrastructure.persistence.repository.JpaPermissionRepository;
import com.inventory.backend.infrastructure.persistence.repository.JpaRoleRepository;
import com.inventory.backend.infrastructure.persistence.repository.JpaUserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.util.Base64;
import java.util.Set;

/**
 * Seeds default roles, permissions, and admin user on initial startup.
 * Admin password is read securely from environment variables, or a secure
 * temporary password is generated on initial seeding if none is provided.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class DataSeeder implements CommandLineRunner {

    private final JpaUserRepository userRepository;
    private final JpaRoleRepository roleRepository;
    private final JpaPermissionRepository permissionRepository;
    private final PasswordEncoder passwordEncoder;

    @Value("${app.seed.enabled:true}")
    private boolean seedEnabled;

    @Value("${app.seed.admin-username:admin}")
    private String adminUsername;

    @Value("${app.seed.admin-email:admin@inventory.com}")
    private String adminEmail;

    @Value("${app.seed.admin-password:}")
    private String adminPassword;

    @Value("${app.seed.admin-fullname:System Administrator}")
    private String adminFullName;

    @Override
    public void run(String... args) {
        if (!seedEnabled) {
            log.info("Initial data seeding is disabled (app.seed.enabled=false).");
            return;
        }

        if (roleRepository.existsByName("ADMIN")) {
            log.info("Roles and users already present in database. Skipping initial seed.");
            return;
        }

        log.info("Seeding initial roles, permissions, and administrator account...");

        // Create permissions
        PermissionEntity userRead = save(perm("USER_READ", "USER", "READ"));
        PermissionEntity userWrite = save(perm("USER_WRITE", "USER", "WRITE"));
        PermissionEntity userDelete = save(perm("USER_DELETE", "USER", "DELETE"));
        PermissionEntity roleRead = save(perm("ROLE_READ", "ROLE", "READ"));
        PermissionEntity roleWrite = save(perm("ROLE_WRITE", "ROLE", "WRITE"));
        PermissionEntity inventoryRead = save(perm("INVENTORY_READ", "INVENTORY", "READ"));
        PermissionEntity inventoryWrite = save(perm("INVENTORY_WRITE", "INVENTORY", "WRITE"));

        // Create roles
        RoleEntity adminRole = roleRepository.save(RoleEntity.builder()
                .name("ADMIN")
                .description("System Administrator with full access")
                .permissions(Set.of(userRead, userWrite, userDelete, roleRead, roleWrite,
                        inventoryRead, inventoryWrite))
                .build());

        RoleEntity managerRole = roleRepository.save(RoleEntity.builder()
                .name("MANAGER")
                .description("Inventory Manager")
                .permissions(Set.of(userRead, inventoryRead, inventoryWrite))
                .build());

        roleRepository.save(RoleEntity.builder()
                .name("STAFF")
                .description("Warehouse Staff")
                .permissions(Set.of(inventoryRead))
                .build());

        // Determine admin password
        String effectivePassword = adminPassword;
        boolean autoGenerated = false;
        if (effectivePassword == null || effectivePassword.isBlank()) {
            effectivePassword = generateSecurePassword();
            autoGenerated = true;
        }

        // Create admin user
        userRepository.save(UserEntity.builder()
                .username(adminUsername)
                .email(adminEmail)
                .passwordHash(passwordEncoder.encode(effectivePassword))
                .fullName(adminFullName)
                .active(true)
                .roles(Set.of(adminRole))
                .build());

        if (autoGenerated) {
            log.warn("================================================================================");
            log.warn("⚠️  SECURITY ALERT: No admin password configured via APP_ADMIN_PASSWORD.");
            log.warn("⚠️  A secure one-time initial password has been generated for '{}':", adminUsername);
            log.warn("⚠️  Temporary Password: {}", effectivePassword);
            log.warn("⚠️  Please change this password immediately after first login!");
            log.warn("================================================================================");
        } else {
            log.info("✅ Initial data seed complete. Administrator account '{}' created.", adminUsername);
        }
    }

    private String generateSecurePassword() {
        byte[] randomBytes = new byte[12];
        new SecureRandom().nextBytes(randomBytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(randomBytes);
    }

    private PermissionEntity save(PermissionEntity p) {
        return permissionRepository.save(p);
    }

    private PermissionEntity perm(String name, String resource, String action) {
        return PermissionEntity.builder()
                .name(name)
                .resource(resource)
                .action(action)
                .build();
    }
}
